name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore dependencies
      run: dotnet restore


    - name: Build MAUI Android Debug
      run: dotnet build -c Debug -f net6.0-android --no-restore
      
    - name: Build MAUI Android Debug Test
      run: dotnet test -c Debug -f net6.0-android --no-build --verbosity normal

    - name: Build MAUI Android Release
      run: dotnet build -c Release -f net6.0-android --no-restore
      
    - name: Build MAUI Android Release Test
      run: dotnet test -c Release -f net6.0-android --no-build --verbosity normal


    #- name: Build MAUI Android
    #  run: dotnet publish -c Release -f net6.0-android --no-restore

    #- name: Upload Android Artifact
    #  uses: actions/upload-artifact@v3.1.0
    #  with:
    #    name: mauibeach-android-ci-build
    #    path: src/MauiBeach/bin/Release/net6.0-android/*Signed.a*
    
    - name: Build MAUI Windows Debug
      run: dotnet build -c Debug -f net6.0-windows10.0.19041.0 --no-restore
      
    - name: Build MAUI Windows Debug Test
      run: dotnet test -c Debug -f net6.0-windows10.0.19041.0 --no-build --no-restore
    
    - name: Build MAUI Windows Release
      run: dotnet build -c Release -f net6.0-windows10.0.19041.0 --no-restore
      
    - name: Build MAUI Windows Release Test
      run: dotnet test -c Release -f net6.0-windows10.0.19041.0 --no-build --no-restore


    #- name: Build MAUI Windows
    #  run: dotnet publish src/MauiBeach/MauiBeach.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore
    
    #- name: Upload Windows Artifact
    #  uses: actions/upload-artifact@v3.1.0
    #  with:
    #    name: mauibeach-windows-ci-build
    #    path: src/MauiBeach/bin/Release/net6.0-windows10.0.19041.0/win10-x64/AppPackages/MauiBeach*/MauiBeach*.msix


    
    - name: Build MAUI iOS Debug
      run: dotnet build  -c Debug -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
        
    - name: Build MAUI iOS Debug Test
      run: dotnet test  -c Debug -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
        
    - name: Build MAUI iOS Release
      run: dotnet build  -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
        
    - name: Build MAUI iOS Release Test
      run: dotnet test  -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False


    #- name: Upload iOS Artifact
    #  uses: actions/upload-artifact@v3.1.0
    #  with:
    #    name: mauibeach-ios-ci-build
    #    path: src/MauiBeach/bin/Release/net6.0-ios/iossimulator-x64/**/*.app


    - name: Build MAUI MacCatalyst Debug
      run: dotnet build -c Debug -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

    - name: Build MAUI MacCatalyst Debug Test
      run: dotnet test -c Debug -f net6.0-maccatalyst --no-restore -p:BuildIpa=True
        
    - name: Build MAUI MacCatalyst Release
      run: dotnet build -c Release -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

    - name: Build MAUI MacCatalyst Release Test
      run: dotnet test -c Release -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

    #- name: Upload MacCatalyst Artifact
    #  uses: actions/upload-artifact@v3.1.0
    #  with:
    #    name: mauibeach-macos-ci-build
    #    path: src/MauiBeach/bin/Release/net6.0-maccatalyst/maccatalyst-x64/publish/*.pkg